version: '3.8'
name: poc_multiple_db_updater

volumes:
  ovalide_data:

services:

  app:
    build: ./app 
    volumes:
      - ovalide_data:/ovalide_data

  db_updater:
    build:
      context: .
      dockerfile: db_updater/Dockerfile
    restart: always
    depends_on:
      - app
    volumes:
    - ovalide_data:/ovalide_data
