version: '2'

services:

  dilavo:
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ovalide_data:/ovalide_data
    ports:
      - "80:3838"
    depends_on:
      - db
        
  db_updater:
    build:
      context: .
      dockerfile: db_updater/Dockerfile
    restart: always
    volumes:
      - ovalide_data:/ovalide_data
    depends_on:
      - db

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    build: ./pgadmin
    restart: always
    ports:
      - "5050:80"
    user: 'root'
    depends_on:
      - dilavo

volumes:
  ovalide_data:
  db_data:
