version: '2'
services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=asdf
    volumes:
      - db_test:/var/lib/postgresql/data

  shiny-app:
    build: .
    environment:
      - R_CONTEXT=dev
    ports:
      - "80:3838"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  db_test:
