version: '3.8'
name: dilavo

volumes:
  ovalide_data:
  db_data:

services:

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  db_setup:
    build: db_setup
    container_name: db_setup
    depends_on:
      - db

  dilavo:
    container_name: shiny_app
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ovalide_data:/ovalide_data
    ports:
      - "80:3838"
    depends_on:
      db_setup:
        condition: service_completed_successfully
        
  db_updater:
    container_name: db_updater
    build:
      context: .
      dockerfile: db_updater/Dockerfile
    restart: always
    volumes:
      - ovalide_data:/ovalide_data
    depends_on:
      db_setup:
        condition: service_completed_successfully


  pgadmin:
    container_name: pgadmin
    build: ./pgadmin
    restart: always
    ports:
      - "5050:80"
    user: 'root'
    depends_on:
      db_setup:
        condition: service_completed_successfully
